[FEATURE] - upgrade to latest version, Kong and KIC
sighupio/fury-kubernetes-kong pull request #4
Opened 2022-04-28 08:51 UTC by nutellinoit

2022-05-10 13:02 UTC, nohant approved these changes

2022-05-11 12:49 UTC, ralgozino requested changes
Hi @nutellinoit 

I left some minor comments for the text in the docs, additionally, here are some questions that come to my mind:

- Do we need the `katalog/kong` folder at all? Being that the module is called `Kong` can we just put all the packages at the `katalog`?
- Why not put `katalog/kong/upstream` folder inside `base`?
- Should add a `MAINTENANCE.md` file?

Thanks!

2022-05-11 12:49 UTC, ralgozino commented on README.md
> +*Kubernetes Fury Kong* contains Kong Ingress Controller for Kubernetes and all the possible deployment options as an
```suggestion
**Kubernetes Fury Kong** contains Kong Ingress Controller for Kubernetes and all the possible deployment options as an
```

2022-05-11 12:49 UTC, ralgozino commented on README.md
> +  Version: Ingress: **2.3.1**, Kong Enterprise: **2.8.1.0**
can we make this a table like we do for the rest of the modules? 
We could have 2 tables, 1 for OSS and 1 for enterprise, or we could add a column saying the package is opensource or enterprise

2022-05-11 12:49 UTC, ralgozino commented on docs/releases/v2.8.1.md
> +Welcome to the latest release of `kong` module of [`Kubernetes Fury
```suggestion
Welcome to the latest release of the `kong` add-on module for [`Kubernetes Fury
```

2022-05-11 12:49 UTC, ralgozino commented on docs/releases/v2.8.1.md
> +This is a minor release with the goal to update kong images and kong ingress controllers to the latest version available.
is `kong` all in underscores the right spelling or should it be `Kong`?

2022-05-11 12:49 UTC, ralgozino commented on docs/releases/v2.8.1.md
> +There will be some downtime while the new version is deployed.
it doesn't do a rolling upgrade?

2022-05-11 12:49 UTC, ralgozino commented on katalog/kong/README.md
> +- Kubernetes - See module compatibility matrix
```suggestion
- Kubernetes - See module [compatibility matrix](https://github.com/sighupio/fury-kubernetes-kong/blob/master/docs/COMPATIBILITY_MATRIX.md)
```

2022-05-11 12:56 UTC, nutellinoit commented on docs/releases/v2.8.1.md
> +There will be some downtime while the new version is deployed.
Yes, but our "deploy" is a DaemonSet with attached services with `externalTrafficPolicy: Local` and in some cases you can have little downtimes

2022-05-11 12:58 UTC, nutellinoit commented on docs/releases/v2.8.1.md
> +This is a minor release with the goal to update kong images and kong ingress controllers to the latest version available.
it's Kong, with capital K

2022-05-11 13:04 UTC, nutellinoit commented on README.md
> +  Version: Ingress: **2.3.1**, Kong Enterprise: **2.8.1.0**
Yes, we can

2022-05-11 13:07 UTC, nutellinoit commented
Hi @ralgozino !

> * Do we need the `katalog/kong` folder at all? Being that the module is called `Kong` can we just put all the packages at the `katalog`?

I prefer to do that on a next major version, Kong 3.0.0 is coming soon

> * Why not put `katalog/kong/upstream` folder inside `base`?

Yes, we can

> * Should add a `MAINTENANCE.md` file?

Yes, but in a different PR, i will open an issue to track it

2022-05-11 14:45 UTC, ralgozino commented
sounds good to me

2022-05-11 15:26 UTC, nutellinoit commented on README.md
> +  Version: Ingress: **2.3.1**, Kong Enterprise: **2.8.1.0**
Done ✅

2022-05-11 15:26 UTC, nutellinoit commented on docs/releases/v2.8.1.md
> +This is a minor release with the goal to update kong images and kong ingress controllers to the latest version available.
Done ✅

2022-05-12 09:47 UTC, ralgozino approved these changes
lgtm

2022-05-12 10:08 UTC, merged